#boson_numbers: [16, 32, 64, 128, 256, 512, 1024]
boson_numbers: [4]
num_repetitions: 1
lammps_exe: "/hirshblab/data/yotamfe1/mlammps/src/lmp_mpi"
baseline_lammps_exe: "/hirshblab/data/yotamfe1/lammps/src/lmp_mpi"
num_beads: 4
